import os
import shutil

# Folder paths
SOURCE_DIR = "../Unit-Testing"
DEST_DIR = "../filtered"

# Create destination folder if not exists
os.makedirs(DEST_DIR, exist_ok=True)

# List of filenames you provided
files_to_move = [
    "Address-Test",
    "AppServiceProvider-Test",
    "AuthController-Test",
    "CompanyCollection-Test",
    "CompanyLogoRequest-Test",
    "CompanyMiddleware-Test",
    "CompanyResource-Test",
    "CompanySetting-Test",
    "Company-Test",
    "CopyModuleController-Test",
    "CountryResource-Test",
    "Country-Test",
    "CreateBackupJob-Test",
    "CronJobMiddleware-Test",
    "CurrencyCollection-Test",
    "CustomField-Test",
    "CustomFieldValue-Test",
    "CustomFieldValueCollection-Test",
    "CustomFieldValueResource-Test",
    "CustomPathGenerator-Test",
    "Customer-Test",
    "CustomerCollection-Test",
    "CustomerEstimateStatusRequest-Test",
    "CustomerMailResetPasswordNotification-Test",
    "CustomerPolicy-Test",
    "CustomerProfileRequest-Test",
    "CustomerRequest-Test",
    "CustomersController-Test",
    "DashboardController-Test",
    "DeleteExpensesRequest-Test",
    "DeleteItemsRequest-Test",
    "DropboxServiceProvider-Test",
    "EmailLog-Test",
    "EnableModuleController-Test",
    "EnvironmentManager-Test",
    "EstimateCollection-Test",
    "EstimateItem-Test",
    "EstimateItemCollection-Test",
    "EstimateItemResource-Test",
    "EstimateResource-Test",
    "EstimateTemplatesController-Test",
    "Estimate-Test",
    "EstimateViewedMail-Test",
    "EstimatesRequest-Test",
    "EventServiceProvider-Test",
    "ExchangeRateLog-Test",
    "ExchangeRateLogCollection-Test",
    "ExchangeRateLogRequest-Test",
    "ExchangeRateLogResource-Test",
    "ExchangeRateProvider-Test",
    "ExchangeRateProviderCollection-Test",
    "ExchangeRateProviderController-Test",
    "ExchangeRateProviderPolicy-Test",
    "ExchangeRateProviderResource-Test",
    "ExchangeRateProvidersTrait-Test",
    "ExpenseCategoriesController-Test",
    "ExpenseCategory-Test",
    "ExpenseCategoryCollection-Test",
    "ExpenseCategoryPolicy-Test",
    "ExpenseCategoryResource-Test",
    "ExpenseCollection-Test",
    "ExpensePolicy-Test",
    "ExpenseRequest-Test",
    "ExpenseResource-Test",
    "Expense-Test",
    "FileDisk-Test",
    "FileDiskCollection-Test",
    "FilePermissionChecker-Test",
    "FilePermissionsController-Test",
    "GeneratesMenuTrait-Test",
    "GeneratesPdfTrait-Test",
    "GetAllUsedCurrenciesController-Test",
    "GetCompanySettingsController-Test",
    "Handler-Test",
    "InstallationMiddleware-Test",
    "Invoice-Test",
    "InvoiceCollection-Test",
    "InvoiceItem-Test",
    "InvoiceItemCollection-Test",
    "InvoiceItemResource-Test",
    "InvoiceResource-Test",
    "InvoiceTemplatesController-Test",
    "InvoiceViewedMail-Test",
    "InvoicesController-Test",
    "InvoicesRequest-Test",
    "ItemCollection-Test",
    "ItemPolicy-Test",
    "ItemResource-Test",
    "ItemSalesReportController-Test",
    "Item-Test",
    "ItemsController-Test",
    "LoginController-Test",
    "MailResetPasswordNotification-Test",
    "ModuleCollection-Test",
    "NextNumberController-Test",
    "Note-Test",
    "NotePolicy-Test",
    "NoteResource-Test",
    "NotesRequest-Test",
    "NumberPlaceholdersController-Test",
    "OnboardingWizardController-Test",
    "Payment-Test",
    "PaymentCollection-Test",
    "PaymentMethod-Test",
    "PaymentMethodCollection-Test",
    "PaymentMethodController-Test",
    "PaymentMethodPolicy-Test",
    "PaymentMethodRequest-Test",
    "ProfileController-Test",
    "ProfileRequest-Test",
    "RecurringInvoice-Test",
    "RecurringInvoiceCollection-Test",
    "RecurringInvoiceFrequencyController-Test",
    "RedirectIfAuthenticated-Test",
    "RedirectIfInstalled-Test",
    "RedirectIfUnauthorized-Test",
    "RegisterController-Test",
    "RelationNotExist-Test",
    "ReportPolicy-Test",
    "ResetApp-Test",
    "ResetPasswordController-Test",
    "RetrospectiveEditsController-Test",
    "RoleCollection-Test",
    "RoleRequest-Test",
    "SendEstimateMail-Test",
    "SendInvoiceMail-Test",
    "SendPaymentMail-Test",
    "Setting-Test",
    "ShowReceiptController-Test",
    "SiteApi-Test",
    "TaxCollection-Test",
    "TaxResource-Test",
    "Tax-Test",
    "Transaction-Test",
    "TransactionCollection-Test",
    "TransactionResource-Test",
    "TrustProxies-Test",
    "Unit-Test",
    "UnitPolicy-Test",
    "UnitRequest-Test",
    "UnitResource-Test",
    "UpdateCompanySettingsController-Test",
    "UpdateController-Test",
    "UpdateSettingsController-Test",
    "Updater-Test",
    "UploadExpenseReceiptRequest-Test",
    "UploadReceiptController-Test",
    "UserCollection-Test",
    "UserRequest-Test",
    "UserSetting-Test",
    "User-Test",
    "UsersController-Test"
]

# Move matching files (any extension)
count = 0
for name in files_to_move:
    for file in os.listdir(SOURCE_DIR):
        if file.startswith(name):
            src = os.path.join(SOURCE_DIR, file)
            dest = os.path.join(DEST_DIR, file)
            shutil.move(src, dest)
            count += 1
            print(f"Moved: {file}")

print(f"\nTotal moved: {count} files.")
